# root directory
dataset_dir: E:\datasets
output_dir: E:\collated_wd

processed_datasets: [CelebDF, DFDC, DFD, FaceForensics++, FakeAVCeleb, SelfGenerated]
#processed_datasets: [CelebDF]

dataset_info:
  CelebDF:
    folder: Celeb-DF-v2
    technique: faceswap
    original: 200 #32
    manipulated: 200 

  DFDC:
    folder: DFDC
    technique: faceswap
    label_file: labels.csv
    original: 200 #45
    manipulated: 200 

  DFD:
    folder: ff-videos
    technique: faceswap
    original: 90 #10
    manipulated: 100 

  FaceForensics++:
    folder: ff-videos
    original: 186 #50
    manipulated: 200 

  FakeAVCeleb:
    folder: FakeAVCeleb_v1.2
    label_file: meta_data.csv
    original: 200 #20
    manipulated: 200

  SelfGenerated:
    folder: self-generated
    technique: lipsync-voiceclone
    original: 5
    manipulated: 5

compression: [c23, c40]
augmentation_techniques: [gra_3, gra_6, ncs_3, ncs_6, dem_3, dem_6, decowa_3, decowa_6, vmifgsm_3, vmifgsm_6]
